Repository Taskify-team4/Taskify, pull requests merged in 2024-04, with the labels that each got.

#12 Chip Component 수정
  components/chip/Chip.tsx
  components/chip/RoundChip.tsx
  components/chip/SquareChip.tsx
  components/chips/Chip.style.ts
  components/chips/Chip.tsx
  components/chips/Chip.type.ts
  components/chips/ColorPalette.tsx
Labels: REFACTOR

#14 Card Component UI 구현
  components/cards/Card.style.ts
  components/cards/Card.tsx
Labels: FEATURE

#18 Modal Input UI 구현
  components/inputs/Input.style.ts
  components/inputs/modalInput/ModalInput.style.ts
  components/inputs/modalInput/ModalInput.tsx
  components/inputs/modalInput/commentInput/CommentInput.style.ts
  components/inputs/modalInput/commentInput/CommentInput.tsx
  components/inputs/modalInput/dateInput/DateInput.style.ts
  components/inputs/modalInput/dateInput/DateInput.tsx
  components/inputs/modalInput/dateInput/DatePicker.tsx
  components/inputs/modalInput/imageInput/ImageInput.style.ts
  components/inputs/modalInput/imageInput/ImageInput.tsx
  components/inputs/modalInput/selectBox/Select.style.ts
  components/inputs/modalInput/selectBox/Select.tsx
  components/inputs/modalInput/selectBox/SelectBox.style.ts
  components/inputs/modalInput/selectBox/SelectBox.tsx
  components/inputs/modalInput/tagInput/TagInput.style.ts
  components/inputs/modalInput/tagInput/TagInput.tsx
  components/inputs/textInput/TextInput.tsx
  package-lock.json
  package.json
  pages/index.tsx
  public/icons/add_violet.svg
  public/icons/check.svg
Labels: FEATURE

#16 Sidemenu Component UI 구현
  components/sidemenu/DashboardList.tsx
  components/sidemenu/Sidemenu.style.ts
  components/sidemenu/Sidemenu.tsx
  components/sidemenu/Sidemenu.type.ts
Labels: FEATURE

#20 비밀번호가 일치하지 않을 때 열리는 모달 UI 구현
  components/modals/ModalBase.tsx
  components/modals/inconsistent_password/Modal.style.ts
  components/modals/inconsistent_password/Modal.tsx
Labels: FEATURE

#22 DateInput 수정
  components/inputs/modalInput/ModalInput.style.ts
  components/inputs/modalInput/commentInput/CommentInput.style.ts
  components/inputs/modalInput/dateInput/DateInput.style.ts
  components/inputs/modalInput/dateInput/DateInput.tsx
  components/inputs/modalInput/dateInput/DatePicker.style.ts
  components/inputs/modalInput/dateInput/DatePicker.tsx
  components/inputs/modalInput/selectBox/Select.style.ts
  components/inputs/modalInput/tagInput/TagInput.style.ts
  pages/index.tsx
Labels: REFACTOR

#23 Header Icon 기능 구현
  components/headers/DashBoardHeader.style.ts
  components/headers/DashBoardHeader.tsx
  components/headers/Header.tsx
  components/headers/Header.type.ts
  components/headers/MainHeader.style.ts
  components/headers/MainHeader.tsx
  components/profileIcon/ProfileIcon.style.ts
  components/profileIcon/ProfileIcon.tsx
  components/profileIcon/ProfileIconContainer.style.ts
  components/profileIcon/ProfileIconContainer.tsx
  utils/stringToColor.ts
Labels: FEATURE

#24 Header 컴포넌트 구현
  components/headers/DashBoardHeader.style.ts
  components/headers/DashBoardHeader.tsx
  components/headers/Header.style.ts
  components/headers/Header.tsx
  components/headers/Header.type.ts
  components/headers/MainHeader.style.ts
  components/headers/MainHeader.tsx
  components/profileIcon/ProfileIcon.style.ts
  components/profileIcon/ProfileIcon.tsx
  components/profileIcon/ProfileIconContainer.style.ts
  components/profileIcon/ProfileIconContainer.tsx
  utils/stringToColor.ts
Labels: FEATURE

#17 Table Component UI 구현
  components/buttons/Button.style.ts
  components/buttons/Button.tsx
  components/buttons/Button.type.ts
  components/table/Table.style.ts
  components/table/Table.type.ts
  components/table/TableHeader.style.ts
  components/table/TableHeader.tsx
  components/table/TableList.style.ts
  components/table/TableList.tsx
  components/table/invite/InviteList.tsx
  components/table/invite/InviteTable.tsx
  components/table/invitedDash/InvitedDashList.tsx
  components/table/invitedDash/InvitedDashTable.tsx
  components/table/invitedDash/SearchBar.style.ts
  components/table/invitedDash/SearchBar.tsx
  components/table/member/MemberList.tsx
  components/table/member/MemberTable.tsx
  public/icons/add_white.svg
  utils/testData.ts
Labels: FEATURE

#28 Modal createtodo, modify 구현
  components/inputs/modalInput/commentInput/CommentInput.style.ts
  components/inputs/modalInput/commentInput/CommentInput.tsx
  components/inputs/modalInput/dateInput/DatePicker.tsx
  components/inputs/modalInput/imageInput/ImageInput.style.ts
  components/inputs/modalInput/imageInput/ImageInput.tsx
  components/inputs/modalInput/selectBox/Select.style.ts
  components/inputs/modalInput/selectBox/Select.tsx
  components/modals/createtodo/Modal.style.ts
  components/modals/createtodo/Modal.tsx
Labels: FEATURE

#32 Modal Task 컴포넌트 UI 구현
  components/modals/modal-task/ModalTask.style.ts
  components/modals/modal-task/ModalTask.tsx
  components/modals/modal-task/TaskChips.tsx
  components/modals/modal-task/TaskComments.tsx
  components/modals/modal-task/TaskContentInfo.tsx
  components/modals/modal-task/TaskDeadline.tsx
Labels: FEATURE

#36 Dashboard 수정 페이지 구현
  components/chips/Chip.style.ts
  components/chips/Chip.type.ts
  components/chips/ColorPalette.tsx
  components/headers/DashBoardHeader.tsx
  components/headers/Header.type.ts
  components/inputs/Input.style.ts
  components/inputs/Input.tsx
  components/inputs/modalInput/ModalInput.tsx
  components/inputs/textInput/TextInput.style.ts
  components/inputs/textInput/TextInput.tsx
  components/modals/edit_dashboard/ConfirmModal.tsx
  components/modals/edit_dashboard/InviteModal.tsx
  components/pages/dashboardEdit/editName/EditName.style.ts
  components/pages/dashboardEdit/editName/EditName.tsx
  components/sidemenu/Sidemenu.type.ts
  components/table/Table.style.ts
  components/table/Table.type.ts
  components/table/TableHeader.tsx
  components/table/TableList.style.ts
  components/table/invite/InviteList.tsx
  components/table/invite/InviteTable.tsx
  components/table/member/MemberList.tsx
  components/table/member/MemberTable.tsx
  constants/breakpointsSize.ts
  constants/error.ts
  constants/page.ts
  package-lock.json
  package.json
  pages/dashboard/[dashboardId]/edit.style.ts
  pages/dashboard/[dashboardId]/edit.tsx
  pages/index.tsx
  utils/breakpointsDevice.ts
  utils/editDashboard/api.ts
  utils/editDashboard/edit.type.ts
Labels: FEATURE

#37 대시보드 page API 연동 및 기능 구현
  components/cards/Card.tsx
  components/chips/Chip.style.ts
  components/inputs/modalInput/ModalInput.tsx
  components/modals/edit_column/Modal.tsx
  components/modals/modal-task/ModalTask.tsx
  components/modals/modal-task/TaskContentInfo.tsx
  components/modals/new_column/Modal.tsx
  components/pages/dashboard/Column.style.ts
  components/pages/dashboard/Column.tsx
  components/sidemenu/DashboardList.tsx
  components/sidemenu/Sidemenu.tsx
  components/sidemenu/Sidemenu.type.ts
  pages/dashboard/Dashboard.type.ts
  pages/dashboard/[dashboardId].tsx
  pages/dashboard/api.ts
  pages/dashboard/index.tsx
  utils/testData.ts
Labels: FEATURE

#39 Login page UI 구현
  components/inputs/Input.style.ts
  components/inputs/passwordInput/PaswwrodInput.style.ts
  components/inputs/textInput/TextInput.style.ts
  components/pages/login/Login.style.ts
  pages/login.tsx
Labels: FEATURE

#40 Signup page UI 구현
  components/pages/signup/Signup.style.ts
  pages/signup.tsx
Labels: FEATURE

#42 Dashboard 수정 페이지 Context 및 커스텀 Hook 적용
  components/chips/ColorPalette.tsx
  components/headers/Header.type.ts
  components/inputs/Input.tsx
  components/inputs/textInput/TextInput.tsx
  components/modals/edit_dashboard/ConfirmModal.tsx
  components/modals/edit_dashboard/InviteModal.tsx
  components/pages/dashboardEdit/editName/EditName.tsx
  components/profileIcon/ProfileIconContainer.tsx
  components/table/Table.type.ts
  components/table/invite/InviteTable.tsx
  components/table/member/MemberList.tsx
  components/table/member/MemberTable.tsx
  contexts/DashboardListContext.tsx
  contexts/myDataContext.tsx
  hooks/useWindowSize.ts
  pages/_app.tsx
  pages/dashboard/[dashboardId]/edit.tsx
  utils/editDashboard/api.ts
  utils/editDashboard/edit.type.ts
  utils/stringToColor.ts
Labels: REFACTOR

#44 Mypage UI 구현
  components/inputs/Input.tsx
  components/inputs/modalInput/imageInput/ImageInput.style.ts
  components/inputs/passwordInput/PasswordInput.tsx
  components/inputs/textInput/TextInput.tsx
  components/pages/myPage/MyPage.style.ts
  components/pages/myPage/password/Password.style.ts
  components/pages/myPage/password/Password.tsx
  components/pages/myPage/profile/Profile.style.ts
  components/pages/myPage/profile/Profile.tsx
  components/sidemenu/Sidemenu.type.ts
  pages/mypage.tsx
Labels: FEATURE

#45 대시보드 수정 페이지 리팩토링
  components/chips/Chip.style.ts
  pages/_app.tsx
  pages/dashboard/[dashboardId]/edit.tsx
  utils/editDashboard/api.ts
Labels: REFACTOR

#46 Landing page topic
  components/headers/Header.style.ts
  components/pages/landing/Landing.type.ts
  components/pages/landing/LandingBody.style.ts
  components/pages/landing/LandingBody.tsx
  components/pages/landing/LandingFooter.style.ts
  components/pages/landing/LandingFooter.tsx
  components/pages/landing/LandingMain.style.ts
  components/pages/landing/LandingMain.tsx
  components/pages/landing/Point1.style.ts
  components/pages/landing/Point1.tsx
  components/pages/landing/Point2.style.ts
  components/pages/landing/Point2.tsx
  components/pages/landing/SettingCard.style.ts
  components/pages/landing/SettingCard.tsx
  components/pages/landing/Settings.style.ts
  components/pages/landing/Settings.tsx
  package-lock.json
  package.json
  pages/landing.style.ts
  pages/landing.tsx
  public/images/point1.png
  public/images/point2.png
  public/images/setting1.png
  public/images/setting2.png
  public/images/setting3.png
Labels: FEATURE

#48 Header issue topic
  components/headers/DashBoardHeader.style.ts
Labels: ISSUE

#50 대시보드 수정 페이지 오류 수정 및 컨텍스트 적용
  components/chips/ColorPalette.tsx
  components/headers/Header.type.ts
  pages/dashboard/Dashboard.type.ts
  pages/dashboard/[dashboardId]/edit.tsx
  utils/editDashboard/api.ts
Labels: ISSUE

#52 Signup page api 연동 및 기능구현
  components/inputs/Input.style.ts
  components/inputs/Input.tsx
  components/inputs/passwordInput/PasswordInput.tsx
  components/inputs/textInput/TextInput.tsx
  components/modals/Modal.tsx
  components/modals/Modal.type.ts
  components/modals/inconsistent_password/Modal.tsx
  pages/login.tsx
  pages/signup.tsx
  utils/dataRegex.ts
Labels: FEATURE

#51 Login page api 연동 및 기능구현
  components/inputs/Input.tsx
  components/inputs/textInput/TextInput.tsx
Labels: FEATURE

#61 대시보드 카드 및 댓글 수정 기능 구현
  components/buttons/Button.tsx
  components/buttons/Button.type.ts
  components/chips/Chip.type.ts
  components/inputs/modalInput/ModalInput.tsx
  components/inputs/modalInput/commentInput/CommentInput.tsx
  components/inputs/modalInput/dateInput/DateInput.tsx
  components/inputs/modalInput/dateInput/DatePicker.tsx
  components/inputs/modalInput/tagInput/TagInput.tsx
  components/modals/createtodo/Modal.tsx
  components/modals/modal-task/ModalTask.style.ts
  components/modals/modal-task/ModalTask.tsx
  components/modals/modal-task/TaskComments.tsx
  components/pages/dashboard/Column.tsx
  next.config.mjs
  pages/dashboard/Dashboard.type.ts
  pages/dashboard/api.ts
Labels: FEATURE

#63 API 통합 리팩토링
  components/chips/ColorPalette.tsx
  components/inputs/modalInput/imageInput/ImageInput.tsx
  components/modals/createtodo/Modal.tsx
  components/modals/edit_column/Modal.tsx
  components/modals/modal-task/ModalTask.tsx
  components/modals/modal-task/TaskComments.tsx
  components/modals/new_column/Modal.tsx
  components/modals/new_dashboard/Modal.tsx
  components/pages/dashboard/Column.tsx
  components/pages/dashboardEdit/editName/EditName.tsx
  components/sidemenu/DashboardList.tsx
  components/sidemenu/Sidemenu.tsx
  components/table/invitedDash/InvitedDashTable.tsx
  contexts/DashboardListContext.tsx
  contexts/dashContext.tsx
  contexts/myDataContext.tsx
  pages/dashboard/Dashboard.type.ts
  pages/dashboard/[dashboardId].tsx
  pages/dashboard/[dashboardId]/edit.tsx
  pages/dashboard/api.ts
  pages/mydashboard/api.ts
  utils/api.ts
  utils/editDashboard/api.ts
Labels: REFACTOR

#67 로그인 정보로 Token 받아오도록 수정
  utils/api.ts
Labels: REFACTOR

#68 Input onChange 함수 수정
  components/inputs/Input.tsx
Labels: REFACTOR

#69 대시보드 리스트 컨텍스트 및 api 호출 함수 코드 리펙토링
  components/buttons/Button.style.ts
  components/buttons/Button.type.ts
  components/headers/DashBoardHeader.style.ts
  components/headers/DashBoardHeader.tsx
  components/headers/Header.type.ts
  components/modals/new_dashboard/Modal.tsx
  components/pages/mydashboard/MyDashboardList.style.ts
  components/pages/mydashboard/MyDashboardList.tsx
  components/sidemenu/DashboardList.tsx
  components/sidemenu/Sidemenu.tsx
  components/table/invitedDash/SearchBar.tsx
  contexts/DashboardListContext.tsx
  contexts/dashContext.tsx
  pages/_app.tsx
  pages/dashboard/[dashboardId]/edit.tsx
  pages/mydashboard/index.tsx
  pages/mydashboard/test.ts
  utils/api.ts
Labels: REFACTOR

#73 myPage API 파일 추가
  components/pages/myPage/password/Password.tsx
  components/pages/myPage/profile/Profile.tsx
  utils/api.ts
Labels: ISSUE

#74 Header 이슈 && 드롭다운 구현
  components/headers/DashBoardHeader.style.ts
  components/headers/DashBoardHeader.tsx
  components/headers/Header.type.ts
  components/pages/myPage/MyPage.style.ts
  components/pages/myPage/profile/Profile.tsx
  pages/mydashboard/index.tsx
  pages/mypage.tsx
Labels: FEATURE, ISSUE

#75 대시보드 각종 이슈 해결(Type 에러, 카드 리렌더링 에러)
  components/inputs/modalInput/commentInput/CommentInput.tsx
  components/inputs/modalInput/selectBox/Select.tsx
  components/inputs/modalInput/selectBox/SelectBox.tsx
  components/inputs/modalInput/tagInput/TagInput.tsx
  components/modals/createtodo/Modal.tsx
  components/modals/edit_column/Modal.tsx
  components/pages/dashboard/Column.tsx
  components/pages/dashboard/ColumnList.tsx
  components/sidemenu/Sidemenu.style.ts
  contexts/dashContext.tsx
  pages/dashboard/Dashboard.type.ts
  utils/api.ts
Labels: REFACTOR

#85 404 페이지 구현
  components/pages/404/404.style.ts
  components/pages/login/Login.style.ts
  pages/404.tsx
Labels: FEATURE

#83 Input type 지정 및 정리
  components/inputs/Input.tsx
  components/inputs/Input.type.ts
  components/inputs/modalInput/ModalInput.tsx
  components/inputs/modalInput/commentInput/CommentInput.tsx
  components/inputs/modalInput/dateInput/DateInput.tsx
  components/inputs/modalInput/dateInput/DatePicker.tsx
  components/inputs/modalInput/imageInput/ImageInput.tsx
  components/inputs/modalInput/selectBox/Select.tsx
  components/inputs/modalInput/selectBox/SelectBox.tsx
  components/inputs/modalInput/tagInput/TagInput.tsx
  components/inputs/passwordInput/PasswordInput.tsx
  components/inputs/textInput/TextInput.tsx
  components/modals/createtodo/Modal.tsx
  components/table/invitedDash/InvitedDashTable.tsx
Labels: REFACTOR

#84 대시보드 수정 페이지 버그 수정
  components/headers/DashBoardHeader.tsx
  components/headers/Header.type.ts
  components/sidemenu/DashboardList.tsx
  components/sidemenu/Sidemenu.tsx
  components/table/Table.type.ts
  components/table/invite/InviteTable.tsx
  components/table/member/MemberTable.tsx
  contexts/dashContext.tsx
  contexts/myDataContext.tsx
  pages/dashboard/[dashboardId].tsx
  pages/dashboard/[dashboardId]/edit.tsx
  pages/dashboard/[dashboardId]/edit.type.ts
  utils/api.ts
Labels: ISSUE

#86 My page 사이드메뉴 항목
  pages/mypage.tsx
Labels: ISSUE

#87 Dropdownmenu z-index 추가
  components/headers/DashBoardHeader.style.ts
Labels: ISSUE

#89 ProfileIcon 이미지 추가
  components/headers/DashBoardHeader.tsx
  components/headers/Header.type.ts
  components/profileIcon/ProfileIcon.style.ts
  components/profileIcon/ProfileIcon.tsx
  components/profileIcon/ProfileIconContainer.tsx
Labels: FEATURE

#90 대시보드 디자인 및 타입 수정
  components/buttons/Button.type.ts
  components/headers/DashBoardHeader.style.ts
  components/inputs/modalInput/ModalInput.tsx
  components/inputs/modalInput/commentInput/CommentInput.tsx
  components/inputs/modalInput/dateInput/DateInput.tsx
  components/modals/createtodo/Modal.tsx
  components/pages/dashboard/Column.style.ts
  pages/dashboard/Dashboard.style.ts
  utils/api.ts
Labels: REFACTOR

#92 My page 뒤로가기 버튼 기능 추가
  components/pages/myPage/MyPage.style.ts
  pages/mypage.tsx
Labels: FEATURE

#95 종합 에러 모음집
  components/cards/Card.tsx
  components/headers/DashBoardHeader.tsx
  components/inputs/Input.type.ts
  components/inputs/modalInput/selectBox/Select.tsx
  components/modals/modal-task/TaskComments.tsx
  components/modals/modal-task/TaskDeadline.tsx
  components/pages/landing/LandingMain.tsx
  components/pages/landing/Point1.tsx
  components/pages/landing/Point2.tsx
  components/pages/landing/SettingCard.tsx
  components/pages/mydashboard/MyDashboardList.tsx
  components/profileIcon/ProfileIcon.style.ts
  components/sidemenu/Sidemenu.tsx
  components/table/TableList.style.ts
  contexts/dashContext.tsx
Labels: ISSUE

#97 새 컬럼 생성 모달 이슈 해결
  components/buttons/Button.style.ts
  components/inputs/Input.type.ts
  components/inputs/modalInput/ModalInput.tsx
  components/modals/new_column/Modal.tsx
  components/table/Table.style.ts
  components/table/Table.type.ts
  pages/dashboard/[dashboardId]/edit.type.ts
Labels: REFACTOR
